### PR TITLE
Updated METAR/TAF service URL. Fixes TH-732

### PR DESCRIPTION
**Pull request by wargoth**
Fixes https://tophatsoaring.atlassian.net/browse/TH-732

### CODE REVIEW

**Comment by rdunning0823** [comment]
I will be traveling until May 28 and will process this pull request then.  Thanks for fixing this.

**Comment by wargoth** [comment]
The last commit implements https://tophatsoaring.atlassian.net/browse/TH-733

**Comment by wargoth** [comment]
I'm not very experienced with C++ and I expect I made a few mistakes, please review carefully

**Review by rdunning0823 — APPROVED** [review]

**Comment by rdunning0823** [comment]
will pull locally

**Review by rdunning0823 — COMMENTED** [review]
What does this commit do?  I did not apply this because I don't understand it.  This appears to integrate with tophat's wind estimate engines.  Can you provide some documentation on exactly how this works?

**Review by krisprolfs — COMMENTED** [review]
new, more recent update for METAR/TAF service URL with https  is needed

**Pull request closed without merging**
